#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: minidlna
# Runs the MiniDLNA daemon
# ==============================================================================
# shellcheck disable=SC1091
#source /usr/lib/hassio-addons/base.sh

# Run the MiniDLNA daemon
exec minidlnad
